#---------------------------------------------------------
# - Setup AWS CLI environment using the secrets from this repo.
# - Try to build and upload the image.
#---------------------------------------------------------
name: Test this action

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # required antecedent
      - uses: actions/checkout@v1

      # required antecedent
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # This action
      - name: Use the action in this repo to Build the image and upload to AWS ECR
        uses: ./
        with:
          aws-ecr-repo: openedx
          custom-theme-repository: 'lpm0073/edx.custom-theme'
          custom-theme-repository-ref: 'master'
          custom-plugin-repository: 'openedx-plugin-example'
          custom-plugin-repository-organization: lpm0073
          custom-plugin-repository-ref: 'main'
          custom-xblock-repository: 'edx-ora2'
          custom-xblock-repository-organization: 'openedx'
          custom-xblock-repository-ref: 'master'
